disableKinds = ["taxonomy", "taxonomyTerm"]
sectionPagesMenu = "main"

[params]
[params.search_config]
app_id = "latency"
api_key = "56f24e4276091e774e8157fe4b8b11f6"
index = "movies"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3"
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss-v5"



