disableKinds = ["taxonomy", "taxonomyTerm"]
sectionPagesMenu = "main"

[params]
[params.searchConfig]
app_id = "latency"
api_key = "56f24e4276091e774e8157fe4b8b11f6"
index = "movies"

[imaging]
resampleFilter = "CatmullRom"
quality = 75
anchor = "smart"

[module]
[[module.imports]]
path = "github.com/bep/hugo-jslibs/alpinejs"
[[module.imports]]
path = "github.com/bep/hugo-jslibs/turbolinks"
[[module.imports]]
path = "github.com/gohugoio/hugo-bootstrap-scss-v4"

